### ISSUE TITLE
Clarifications regarding training dataset features

### ISSUE THREAD

**Issue by ScubaChris** [jas-preet/SPOT-1D-LM#3]
Hello and thank you for your work,

Your starting dataset is ProteinNet, but it does not seem to include the features you are predicting for. SidechainNet has some of those features but not all (ex. ASA, HSE, CN). Did you use custom scripts to generate all the above features for your training, and if so, are those scripts/features available somewhere in one of the repos? (apologies if they exist and I've missed them)

**Comment by jas-preet** [comment]
While I appreciate your interest in the custom scripts used for feature generation, I regret to inform you that they are currently unavailable due to several factors. Firstly, these scripts were developed during my PhD research and may not be adequately documented or maintained for public use. Secondly, due to limited resources, I am unable to actively maintain this repository or provide extensive support for it.
