### ISSUE TITLE
Cannot Download Checkpoint

### ISSUE THREAD

**Issue by jane-pyc** [jas-preet/SPOT-1D-LM#4]
hello, it seems that your server has been down, I couldn't download your model checkpoint.

Could you please help me resolve this?

Thanks!

**Comment by sroseallen** [comment]
Hello, I also seem to be having the same problem - here is the error code I am getting (I assume it's related to the server being down?):

wget https://servers.sparks-lab.org/downloads/SPOT-LM-checkpoints.xz
--2023-08-30 18:05:52--  https://servers.sparks-lab.org/downloads/SPOT-LM-checkpoints.xz 
Resolving servers.sparks-lab.org (servers.sparks-lab.org)... 172.67.130.213, 104.21.3.148, 2606:4700:3031::6815:394, ...
Connecting to servers.sparks-lab.org (servers.sparks-lab.org)|172.67.130.213|:443... connected.
HTTP request sent, awaiting response... 522
2023-08-30 18:06:24 ERROR 522: (no description).

**Comment by lm-jkominek** [comment]
I am not the author, and I am not sure if you still care after all this time, but just wanted to let you know that the SPOT-1D-LM model checkpoints can be downloaded from this location - https://apisz.sparks-lab.org:8443/downloads/Resource/Protein/2_Protein_local_structure_prediction/SPOT-LM-checkpoints.xz

(luckily someone had a similar issue with SPOT-1D-Single, and got an answer - https://github.com/jas-preet/SPOT-1D-Single/issues/2)

**Comment by jas-preet** [comment]
Thanks for the members of community to support and respond the questions. I have taken help from your responses and updated the code with the correct link and facilitate the checkpoint downloads. 
Additionally, apologies for delayed response as this work was developed during my PhD research and currently due to other engagements I am unable to provide the required support.
