### ISSUE TITLE
Please release training and estimation codes, as well as dataset details.

### ISSUE THREAD

**Issue by brian-zZZ** [jas-preet/SPOT-1D-LM#6]
Hello and thank for your work!

I found that only the inference code has been released, while the model training code and the method to estimate the performance of predicted result are not declared. Besides, there is very little information on the dataset that I couldn't find a way to download it. Lacking these information I can't reproduce the results, colud you please provide them, which will help me a lot.

Thank!

**Comment by jas-preet** [comment]
While I appreciate your interest in the training, estimation codes and dataset details, I regret to inform you that they are currently unavailable due to several factors. Firstly, these scripts were developed during my PhD research and may not be adequately documented or maintained for public use. Secondly, due to limited resources, I am unable to actively maintain this repository or provide extensive support for it.
